{
    cpu: {
        icache: {
            size: 16384,
            line_size: 32,
            num_ways: 4
        },
        dcache: {
            size: 16384,
            line_size: 32,
            num_ways: 4
        },
        itlb: {
            num_entries: 8
        },
        dtlb: {
            num_entries: 8
        },
        manufacturer: 0x4a49,
        model: 0x0001,
        clock_speed: 50000000
    },
    peripherals: [
        {
            name: ram,
            address: "0x0000000",
            size: "0x0001000"
        },
        {
            name: bootrom,
            address: "0x10000000",
            size: "0x0004000"
        },
        {
            name: sdram,
            address: "0x20000000",
            size: "0x04000000"
        },
        {
            name: sdram_ctrl,
            address: "0x80001000",
            size: "0x00001000",
            regmap: sdram_ctrl
        },
        {
            name: uart,
            address: "0x80000000",
            size: "0x0001000",
            regmap: uart
        },
        {
            name: irq,
            address: "0x80002000",
            size: "0x00001000",
            regmap: irq_ctrl,
        },
        {
            name: timer,
            address: "0x80003000",
            size: "0x00001000",
            regmap: timer,
            interrupts: [0, 1, 2, 3]
        },
        {
            name: spimaster,
            address: "0x80004000",
            size: "0x00004000",
            regmap: spimaster
        },
        # Two banks of GPIO:
        #   - bank 1 at offset 16
        #     - [31:28]: push buttons
        #     - [27:26]: no connection
        #     - [25:16]: switches
        #     - [15:15]: no connection
        #     - [14:8]: 7-seg 5
        #     - [7:7]: no connection
        #     - [7:0]: 7-seg 4
        #   - bank 0 at offset 0
        #     - [30:24]: 7-seg 3
        #     - [22:16]: 7-seg 2
        #     - [14:8]: 7-seg 1
        #     - [6:0]: 7-seg 0
        {
            name: gpio,
            address: "0x80008000",
            size: "0x00001000",
            regmap: gpio
        }
    ]
}
